import { RoomType, Tile, GuardEntity, CameraEntity, LaserBeam, TerminalEntity, ItemDrop, BossEntity } from '../types';

export const ROOM_WIDTH = 15;
export const ROOM_HEIGHT = 11;
export const TILE_SIZE = 48; // in pixels

// Center door positions
export const DOOR_N = { x: 7, y: 0 };
export const DOOR_S = { x: 7, y: 10 };
export const DOOR_W = { x: 0, y: 5 };
export const DOOR_E = { x: 14, y: 5 };
export const CENTER_TILE = { x: 7, y: 5 };

export interface PrefabTemplate {
  type: RoomType;
  name: string;
  description: string;
  // Layout representation: 11 rows of 15 chars
  // '#' = wall, '.' = floor, 'c' = cover/desk, 't' = terminal, 'x' = hazard, 'e' = elevator
  layout: string[];
  spawnGuards?: (roomWorldX: number, roomWorldY: number) => GuardEntity[];
  spawnCameras?: (roomWorldX: number, roomWorldY: number) => CameraEntity[];
  spawnLasers?: (roomWorldX: number, roomWorldY: number) => LaserBeam[];
  spawnTerminals?: (roomWorldX: number, roomWorldY: number) => TerminalEntity[];
  spawnItems?: (roomWorldX: number, roomWorldY: number) => ItemDrop[];
  spawnBoss?: (roomWorldX: number, roomWorldY: number) => BossEntity;
}

export const PREFABS: Record<RoomType, PrefabTemplate[]> = {
  START: [
    {
      type: 'START',
      name: 'Conducto de Inserción 077',
      description: 'Punto de infiltración seguro. Sin actividad hostil detectada.',
      layout: [
        '###############',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#.............#',
        '#......t......#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '###############',
      ],
      spawnTerminals: (wx, wy) => [
        {
          id: `term_start_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          hacked: false,
          hackProgress: 0,
          type: 'map_reveal',
          label: 'Descargar Planos de Seguridad',
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_ammo_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 4 * TILE_SIZE + 24,
          y: wy + 3 * TILE_SIZE + 24,
          type: 'ammo',
          amount: 14,
          name: 'Munición 9mm Silenciada',
        },
        {
          id: `item_emp_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 10 * TILE_SIZE + 24,
          y: wy + 3 * TILE_SIZE + 24,
          type: 'emp_charge',
          amount: 2,
          name: 'Dardo EMP',
        },
      ],
    },
  ],

  PATROL: [
    {
      type: 'PATROL',
      name: 'Cuartel de Vigilancia Alfa',
      description: 'Sector con patrullas activas de guardias armados y puestos de guardia.',
      layout: [
        '###############',
        '#.............#',
        '#...c.....c...#',
        '#...c.....c...#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#...c.....c...#',
        '#...c.....c...#',
        '#.............#',
        '###############',
      ],
      spawnGuards: (wx, wy) => [
        {
          id: `guard_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 3 * TILE_SIZE + 24,
          y: wy + 2 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: 0,
          speed: 55,
          patrolPoints: [
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 2 * TILE_SIZE + 24 },
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 2 * TILE_SIZE + 24 },
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 8 * TILE_SIZE + 24 },
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 8 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 60,
          maxHealth: 60,
          shootCooldown: 0,
          fovAngle: (70 * Math.PI) / 180,
          fovDistance: 190,
        },
        {
          id: `guard_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 11 * TILE_SIZE + 24,
          y: wy + 8 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: Math.PI,
          speed: 50,
          patrolPoints: [
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 8 * TILE_SIZE + 24 },
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 8 * TILE_SIZE + 24 },
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 2 * TILE_SIZE + 24 },
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 2 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 60,
          maxHealth: 60,
          shootCooldown: 0,
          fovAngle: (70 * Math.PI) / 180,
          fovDistance: 190,
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 3 * TILE_SIZE + 24,
          type: 'ammo',
          amount: 8,
          name: 'Munición 9mm',
        },
      ],
    },
    {
      type: 'PATROL',
      name: 'Depósito de Logística Militar',
      description: 'Almacén con cobertura y centinela táctico.',
      layout: [
        '###############',
        '#..c.......c..#',
        '#.............#',
        '#....c...c....#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#....c...c....#',
        '#.............#',
        '#..c.......c..#',
        '###############',
      ],
      spawnGuards: (wx, wy) => [
        {
          id: `guard_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 3 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: Math.PI / 2,
          speed: 60,
          patrolPoints: [
            { x: wx + 7 * TILE_SIZE + 24, y: wy + 3 * TILE_SIZE + 24 },
            { x: wx + 7 * TILE_SIZE + 24, y: wy + 7 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 60,
          maxHealth: 60,
          shootCooldown: 0,
          fovAngle: (75 * Math.PI) / 180,
          fovDistance: 180,
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_med_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 2 * TILE_SIZE + 24,
          y: wy + 2 * TILE_SIZE + 24,
          type: 'medkit',
          amount: 40,
          name: 'Botiquín de Inyección Rápida',
        },
      ],
    },
  ],

  LASER_GRID: [
    {
      type: 'LASER_GRID',
      name: 'Corredor de Cuadrícula Láser',
      description: 'Pasillo de alta seguridad protegido por barreras láser intermitentes.',
      layout: [
        '###############',
        '#..c.......c..#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '###############',
      ],
      spawnLasers: (wx, wy) => [
        {
          id: `laser_h1_${Math.random().toString(36).substr(2, 5)}`,
          x1: wx + 2 * TILE_SIZE,
          y1: wy + 3 * TILE_SIZE,
          x2: wx + 13 * TILE_SIZE,
          y2: wy + 3 * TILE_SIZE,
          active: true,
          cyclePeriod: 3.5,
          activeDuration: 2.0,
          timer: 0,
          horizontal: true,
        },
        {
          id: `laser_h2_${Math.random().toString(36).substr(2, 5)}`,
          x1: wx + 2 * TILE_SIZE,
          y1: wy + 7 * TILE_SIZE,
          x2: wx + 13 * TILE_SIZE,
          y2: wy + 7 * TILE_SIZE,
          active: false,
          cyclePeriod: 3.5,
          activeDuration: 2.0,
          timer: 1.7,
          horizontal: true,
        },
      ],
      spawnGuards: (wx, wy) => [
        {
          id: `guard_laser_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 12 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: Math.PI,
          speed: 40,
          patrolPoints: [
            { x: wx + 12 * TILE_SIZE + 24, y: wy + 5 * TILE_SIZE + 24 },
            { x: wx + 10 * TILE_SIZE + 24, y: wy + 5 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 50,
          maxHealth: 50,
          shootCooldown: 0,
          fovAngle: (60 * Math.PI) / 180,
          fovDistance: 170,
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_smoke_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          type: 'smoke_grenade',
          amount: 1,
          name: 'Granada de Humo',
        },
      ],
    },
  ],

  SERVER_HUB: [
    {
      type: 'SERVER_HUB',
      name: 'Centro de Servidores Criptográficos',
      description: 'Nodo central de datos. Permite hackear terminales para anular alarmas y cámaras.',
      layout: [
        '###############',
        '#..c.......c..#',
        '#..c.......c..#',
        '#.............#',
        '#....c...c....#',
        '#....c.t.c....#',
        '#....c...c....#',
        '#.............#',
        '#..c.......c..#',
        '#..c.......c..#',
        '###############',
      ],
      spawnTerminals: (wx, wy) => [
        {
          id: `term_hub_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          hacked: false,
          hackProgress: 0,
          type: 'alarm_reset',
          label: 'Anular Alarma y Congelar Cámaras',
        },
      ],
      spawnGuards: (wx, wy) => [
        {
          id: `guard_server_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 3 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: 0,
          speed: 45,
          patrolPoints: [
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 5 * TILE_SIZE + 24 },
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 3 * TILE_SIZE + 24 },
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 3 * TILE_SIZE + 24 },
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 7 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 70,
          maxHealth: 70,
          shootCooldown: 0,
          fovAngle: (70 * Math.PI) / 180,
          fovDistance: 180,
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_intel_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 12 * TILE_SIZE + 24,
          y: wy + 2 * TILE_SIZE + 24,
          type: 'intel',
          amount: 1,
          name: 'Disco Cifrado Confidencial',
        },
      ],
    },
  ],

  ARMORY: [
    {
      type: 'ARMORY',
      name: 'Armería de Operaciones Especiales',
      description: 'Depósito clasificado con suministros tácticos y equipo de infiltración.',
      layout: [
        '###############',
        '#..c...t...c..#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '###############',
      ],
      spawnTerminals: (wx, wy) => [
        {
          id: `term_armory_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 1 * TILE_SIZE + 24,
          hacked: false,
          hackProgress: 0,
          type: 'boss_override',
          label: 'Descifrar Clave de la Puerta del Jefe',
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_key_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          type: 'keycard',
          amount: 1,
          name: 'Tarjeta de Acceso Alfa',
        },
        {
          id: `item_emp2_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 4 * TILE_SIZE + 24,
          y: wy + 6 * TILE_SIZE + 24,
          type: 'emp_charge',
          amount: 2,
          name: 'Dardos EMP de Alta Frecuencia',
        },
        {
          id: `item_med2_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 10 * TILE_SIZE + 24,
          y: wy + 6 * TILE_SIZE + 24,
          type: 'medkit',
          amount: 50,
          name: 'Estimulante Adrenalínico',
        },
        {
          id: `item_ammo3_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 7 * TILE_SIZE + 24,
          type: 'ammo',
          amount: 16,
          name: 'Cargadores Subsónicos',
        },
      ],
    },
  ],

  CCTV_ROOM: [
    {
      type: 'CCTV_ROOM',
      name: 'Sala de Monitoreo y Circuito Cerrado',
      description: 'Cámaras de vigilancia activas que activan la alarma si te detectan.',
      layout: [
        '###############',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '###############',
      ],
      spawnCameras: (wx, wy) => [
        {
          id: `cam_1_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 1 * TILE_SIZE + 24,
          y: wy + 1 * TILE_SIZE + 24,
          angle: Math.PI / 4,
          minAngle: 0,
          maxAngle: Math.PI / 2,
          sweepSpeed: 0.8,
          sweepDir: 1,
          fovAngle: (50 * Math.PI) / 180,
          fovDistance: 220,
          disabled: false,
          disableTimer: 0,
        },
        {
          id: `cam_2_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 13 * TILE_SIZE + 24,
          y: wy + 9 * TILE_SIZE + 24,
          angle: (5 * Math.PI) / 4,
          minAngle: Math.PI,
          maxAngle: (3 * Math.PI) / 2,
          sweepSpeed: 0.8,
          sweepDir: -1,
          fovAngle: (50 * Math.PI) / 180,
          fovDistance: 220,
          disabled: false,
          disableTimer: 0,
        },
      ],
      spawnGuards: (wx, wy) => [
        {
          id: `guard_cctv_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 5 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: 0,
          speed: 40,
          patrolPoints: [
            { x: wx + 5 * TILE_SIZE + 24, y: wy + 5 * TILE_SIZE + 24 },
            { x: wx + 9 * TILE_SIZE + 24, y: wy + 5 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 65,
          maxHealth: 65,
          shootCooldown: 0,
          fovAngle: (70 * Math.PI) / 180,
          fovDistance: 190,
        },
      ],
    },
  ],

  LABORATORY: [
    {
      type: 'LABORATORY',
      name: 'Laboratorio de Investigación Secreta',
      description: 'Complejo biotecnológico con materiales clasificados y agentes de choque.',
      layout: [
        '###############',
        '#...c.....c...#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#...c.....c...#',
        '###############',
      ],
      spawnGuards: (wx, wy) => [
        {
          id: `guard_heavy_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 3 * TILE_SIZE + 24,
          vx: 0,
          vy: 0,
          angle: Math.PI / 2,
          speed: 45,
          patrolPoints: [
            { x: wx + 7 * TILE_SIZE + 24, y: wy + 3 * TILE_SIZE + 24 },
            { x: wx + 11 * TILE_SIZE + 24, y: wy + 7 * TILE_SIZE + 24 },
            { x: wx + 3 * TILE_SIZE + 24, y: wy + 7 * TILE_SIZE + 24 },
          ],
          currentPatrolIdx: 0,
          state: 'patrol',
          alertMeter: 0,
          health: 120,
          maxHealth: 120,
          shootCooldown: 0,
          fovAngle: (80 * Math.PI) / 180,
          fovDistance: 200,
          isHeavy: true,
        },
      ],
      spawnItems: (wx, wy) => [
        {
          id: `item_intel_${Math.random().toString(36).substr(2, 5)}`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 7 * TILE_SIZE + 24,
          type: 'intel',
          amount: 2,
          name: 'Prototipo de Suero 077',
        },
      ],
    },
  ],

  BOSS: [
    {
      type: 'BOSS',
      name: 'Búnker de Mando: Dr. Voronin',
      description: 'El núcleo de mando de la base. Elimina al comandante supremo o hackea su consola para acceder al ascensor.',
      layout: [
        '###############',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '#.............#',
        '#......e......#',
        '#.............#',
        '#.............#',
        '#..c.......c..#',
        '#.............#',
        '###############',
      ],
      spawnBoss: (wx, wy) => ({
        id: 'boss_voronin',
        x: wx + 7 * TILE_SIZE + 24,
        y: wy + 3 * TILE_SIZE + 24,
        angle: Math.PI / 2,
        health: 280,
        maxHealth: 280,
        phase: 1,
        shield: 100,
        maxShield: 100,
        attackCooldown: 1.5,
        state: 'idle',
        defeated: false,
      }),
      spawnTerminals: (wx, wy) => [
        {
          id: `term_boss_core`,
          x: wx + 7 * TILE_SIZE + 24,
          y: wy + 2 * TILE_SIZE + 24,
          hacked: false,
          hackProgress: 0,
          type: 'boss_override',
          label: 'Descifrar Protocolo de Extracción',
        },
      ],
    },
  ],
};
